DELETE FROM `m_permission` WHERE code in ('DEPOSIT_SAVINGSACCOUNTNUMBER','WITHDRAWAL_SAVINGSACCOUNTNUMBER','DEPOSIT2_SAVINGSACCOUNTNUMBER','WITHDRAWAL2_SAVINGSACCOUNTNUMBER');

INSERT INTO `m_permission` (`grouping`, `code`, `entity_name`, `action_name`, `can_maker_checker`)
VALUES ('portfolio', 'DEPOSIT_SAVINGSACCOUNTNUMBER', 'SAVINGSACCOUNTNUMBER', 'DEPOSIT', 0)
,('portfolio', 'WITHDRAWAL_SAVINGSACCOUNTNUMBER', 'SAVINGSACCOUNTNUMBER', 'WITHDRAWAL', 0)
,('portfolio', 'DEPOSIT2_SAVINGSACCOUNTNUMBER', 'SAVINGSACCOUNTNUMBER', 'DEPOSIT2', 0)
,('portfolio', 'WITHDRAWAL2_SAVINGSACCOUNTNUMBER', 'SAVINGSACCOUNTNUMBER', 'WITHDRAWAL2', 0);