DELETE FROM `m_permission` WHERE code in ('WITHDRAWALBATCHTRANSACTION2_SAVINGSACCOUNT','DEPOSITBATCHTRANSACTION2_SAVINGSACCOUNT');

INSERT INTO `m_permission` (`id`, `grouping`, `code`, `entity_name`, `action_name`, `can_maker_checker`) VALUES 
(NULL, 'portfolio', 'WITHDRAWALBATCHTRANSACTION2_SAVINGSACCOUNT', 'SAVINGSACCOUNT', 'WITHDRAWALBATCHTRANSACTION2', '1'), 
(NULL, 'portfolio', 'DEPOSITBATCHTRANSACTION2_SAVINGSACCOUNT', 'SAVINGSACCOUNT', 'DEPOSITBATCHTRANSACTION2', '1');